In [1]:
# Add directory above current directory to path
import sys as SYS; SYS.path.insert(0, '..')

# for saving
import os

from collections import defaultdict
import numpy as np
import matplotlib.pyplot as plt

from src import setup
# setup.use_gpu()

In [2]:
from src import ( 
    measurements as measure,
    density_matrix as DM,
    simulation as sim,
    orders,
    order_rules,
    random_unitary,
    simulation)

from Scripts import simulation_CLI as cleo

In [3]:
import matplotlib.pyplot as plt 
import matplotlib.colors as mcolors 

import matplotlib.animation as animation
# Add directory above current directory to path
import sys as SYS; SYS.path.insert(0, '../..')
import h5py
import networkx as nx
import matplotlib.pyplot as plt
import numpy as np
from src import ket as ket
from src import density_matrix as DM

In [7]:
G1edges=[np.array([[ 0., 81., 70., 70., 57., 86., 72., 63.],
       [81.,  0., 77., 70., 53., 69., 78., 71.],
       [70., 77.,  0., 74., 70., 73., 74., 61.],
       [70., 70., 74.,  0., 79., 65., 65., 76.],
       [57., 53., 70., 79.,  0., 85., 66., 89.],
       [86., 69., 73., 65., 85.,  0., 63., 58.],
       [72., 78., 74., 65., 66., 63.,  0., 81.],
       [63., 71., 61., 76., 89., 58., 81.,  0.]]),np.array([[ 0., 71., 72., 73., 65., 76., 78., 64.],
       [71.,  0., 57., 85., 60., 82., 74., 70.],
       [72., 57.,  0., 64., 83., 68., 69., 86.],
       [73., 85., 64.,  0., 76., 72., 60., 69.],
       [65., 60., 83., 76.,  0., 64., 78., 73.],
       [76., 82., 68., 72., 64.,  0., 70., 67.],
       [78., 74., 69., 60., 78., 70.,  0., 70.],
       [64., 70., 86., 69., 73., 67., 70.,  0.]]),np.array([[ 0., 78., 63., 93., 76., 92., 49., 48.],
       [78.,  0., 77., 60., 75., 80., 70., 59.],
       [63., 77.,  0., 76., 54., 76., 68., 85.],
       [93., 60., 76.,  0., 84., 52., 52., 82.],
       [76., 75., 54., 84.,  0., 48., 85., 77.],
       [92., 80., 76., 52., 48.,  0., 89., 62.],
       [49., 70., 68., 52., 85., 89.,  0., 86.],
       [48., 59., 85., 82., 77., 62., 86.,  0.]]),np.array([[  0.,   0.,   1.,   0.,   1., 493.,   3.,   1.],
       [  0.,   0.,   1.,   2., 493.,   1.,   0.,   2.],
       [  1.,   1.,   0.,   1.,   1.,   0.,   2., 493.],
       [  0.,   2.,   1.,   0.,   3.,   1., 492.,   0.],
       [  1., 493.,   1.,   3.,   0.,   1.,   0.,   0.],
       [493.,   1.,   0.,   1.,   1.,   0.,   1.,   2.],
       [  3.,   0.,   2., 492.,   0.,   1.,   0.,   1.],
       [  1.,   2., 493.,   0.,   0.,   2.,   1.,   0.]])];

In [8]:
G2edges=[np.array([[0.        , 0.00447126, 0.00462432, 0.00311855, 0.00334066,
        0.00236682, 0.00439406, 0.00466434],
       [0.00447126, 0.        , 0.00441267, 0.0027655 , 0.00371087,
        0.00189819, 0.00386997, 0.0030265 ],
       [0.00462432, 0.00441267, 0.        , 0.00345204, 0.00560786,
        0.00269925, 0.00445565, 0.00368035],
       [0.00311855, 0.0027655 , 0.00345204, 0.        , 0.00252231,
        0.00318034, 0.00365139, 0.00193529],
       [0.00334066, 0.00371087, 0.00560786, 0.00252231, 0.        ,
        0.00189649, 0.00339318, 0.00368068],
       [0.00236682, 0.00189819, 0.00269925, 0.00318034, 0.00189649,
        0.        , 0.00203322, 0.00231932],
       [0.00439406, 0.00386997, 0.00445565, 0.00365139, 0.00339318,
        0.00203322, 0.        , 0.00256445],
       [0.00466434, 0.0030265 , 0.00368035, 0.00193529, 0.00368068,
        0.00231932, 0.00256445, 0.        ]]),np.array([[0.        , 0.00233122, 0.00292562, 0.00242988, 0.0021096 ,
        0.0029352 , 0.00213344, 0.00368767],
       [0.00233122, 0.        , 0.00203821, 0.00284457, 0.00194883,
        0.00301986, 0.0018486 , 0.00193986],
       [0.00292562, 0.00203821, 0.        , 0.00417222, 0.00363315,
        0.00419894, 0.00349049, 0.00540057],
       [0.00242988, 0.00284457, 0.00417222, 0.        , 0.00464348,
        0.00366689, 0.00302191, 0.00560361],
       [0.0021096 , 0.00194883, 0.00363315, 0.00464348, 0.        ,
        0.0025402 , 0.00249324, 0.0032672 ],
       [0.0029352 , 0.00301986, 0.00419894, 0.00366689, 0.0025402 ,
        0.        , 0.00406623, 0.00516302],
       [0.00213344, 0.0018486 , 0.00349049, 0.00302191, 0.00249324,
        0.00406623, 0.        , 0.00340951],
       [0.00368767, 0.00193986, 0.00540057, 0.00560361, 0.0032672 ,
        0.00516302, 0.00340951, 0.        ]]),np.array([[0.        , 0.00306659, 0.00345463, 0.00383706, 0.0040359 ,
        0.00320574, 0.0033893 , 0.00346077],
       [0.00306659, 0.        , 0.00212126, 0.00223934, 0.00216582,
        0.00245015, 0.00188453, 0.00202523],
       [0.00345463, 0.00212126, 0.        , 0.00312238, 0.00329954,
        0.00428732, 0.00386886, 0.00241225],
       [0.00383706, 0.00223934, 0.00312238, 0.        , 0.00398433,
        0.00350584, 0.00251622, 0.00307493],
       [0.0040359 , 0.00216582, 0.00329954, 0.00398433, 0.        ,
        0.00300407, 0.00365506, 0.00301485],
       [0.00320574, 0.00245015, 0.00428732, 0.00350584, 0.00300407,
        0.        , 0.00796979, 0.00412459],
       [0.0033893 , 0.00188453, 0.00386886, 0.00251622, 0.00365506,
        0.00796979, 0.        , 0.00264932],
       [0.00346077, 0.00202523, 0.00241225, 0.00307493, 0.00301485,
        0.00412459, 0.00264932, 0.        ]]),np.array([[0.        , 0.00204384, 0.00674182, 0.00680605, 0.02773628,
        0.00196032, 0.0077259 , 0.00581472],
       [0.00204384, 0.        , 0.00253247, 0.00427025, 0.0029081 ,
        0.00129849, 0.00077398, 0.00093111],
       [0.00674182, 0.00253247, 0.        , 0.01065028, 0.00661111,
        0.00434258, 0.00236082, 0.00159202],
       [0.00680605, 0.00427025, 0.01065028, 0.        , 0.01605909,
        0.00740731, 0.00419034, 0.00265644],
       [0.02773628, 0.0029081 , 0.00661111, 0.01605909, 0.        ,
        0.00459017, 0.01682413, 0.00948628],
       [0.00196032, 0.00129849, 0.00434258, 0.00740731, 0.00459017,
        0.        , 0.00285876, 0.00072507],
       [0.0077259 , 0.00077398, 0.00236082, 0.00419034, 0.01682413,
        0.00285876, 0.        , 0.00282383],
       [0.00581472, 0.00093111, 0.00159202, 0.00265644, 0.00948628,
        0.00072507, 0.00282383, 0.        ]])];

In [14]:
G1edges[3]

array([[  0.,   0.,   1.,   0.,   1., 493.,   3.,   1.],
       [  0.,   0.,   1.,   2., 493.,   1.,   0.,   2.],
       [  1.,   1.,   0.,   1.,   1.,   0.,   2., 493.],
       [  0.,   2.,   1.,   0.,   3.,   1., 492.,   0.],
       [  1., 493.,   1.,   3.,   0.,   1.,   0.,   0.],
       [493.,   1.,   0.,   1.,   1.,   0.,   1.,   2.],
       [  3.,   0.,   2., 492.,   0.,   1.,   0.,   1.],
       [  1.,   2., 493.,   0.,   0.,   2.,   1.,   0.]])

In [15]:
G2edges[3]

array([[0.        , 0.00204384, 0.00674182, 0.00680605, 0.02773628,
        0.00196032, 0.0077259 , 0.00581472],
       [0.00204384, 0.        , 0.00253247, 0.00427025, 0.0029081 ,
        0.00129849, 0.00077398, 0.00093111],
       [0.00674182, 0.00253247, 0.        , 0.01065028, 0.00661111,
        0.00434258, 0.00236082, 0.00159202],
       [0.00680605, 0.00427025, 0.01065028, 0.        , 0.01605909,
        0.00740731, 0.00419034, 0.00265644],
       [0.02773628, 0.0029081 , 0.00661111, 0.01605909, 0.        ,
        0.00459017, 0.01682413, 0.00948628],
       [0.00196032, 0.00129849, 0.00434258, 0.00740731, 0.00459017,
        0.        , 0.00285876, 0.00072507],
       [0.0077259 , 0.00077398, 0.00236082, 0.00419034, 0.01682413,
        0.00285876, 0.        , 0.00282383],
       [0.00581472, 0.00093111, 0.00159202, 0.00265644, 0.00948628,
        0.00072507, 0.00282383, 0.        ]])

In [22]:
import networkx as nx
import numpy as np
from scipy.stats import pearsonr, spearmanr


import networkx as nx
import numpy as np

# Example adjacency matrix (numpy array)
adj_matrix_G1 = G1edges[3]

adj_matrix_G2 = G2edges[3]

# Function to convert adjacency matrix to edge list
def adj_matrix_to_edge_list(adj_matrix):
    edge_list = []
    num_nodes = adj_matrix.shape[0]
    for i in range(num_nodes):
        for j in range(i+1, num_nodes):  # Only consider upper triangle for undirected graph
            if adj_matrix[i, j] != 0:
                edge_list.append((i, j, adj_matrix[i, j]))  # (node1, node2, weight)
    return edge_list

# Convert adjacency matrices to edge lists
G1_edges = adj_matrix_to_edge_list(adj_matrix_G1)
G2_edges = adj_matrix_to_edge_list(adj_matrix_G2)



# Print the graphs' edges to verify
print("G1 edges:", G1.edges(data=True))
print("G2 edges:", G2.edges(data=True))


# Function to extract edge weights from a graph
def get_edge_weights(graph):
    edge_weights = {}
    for (u, v, w) in graph.edges(data='weight'):
        edge_weights[(u, v)] = w
    return edge_weights

# Function to align edge weights of two graphs
def align_edge_weights(g1_weights, g2_weights):
    common_edges = set(g1_weights.keys()).intersection(g2_weights.keys())
    g1_aligned = [g1_weights[edge] for edge in common_edges]
    g2_aligned = [g2_weights[edge] for edge in common_edges]
    return g1_aligned, g2_aligned

# Pearson and Spearman correlation calculation
def calculate_edge_correlations(G1, G2):
    # Extract edge weights from both graphs
    g1_weights = get_edge_weights(G1)
    g2_weights = get_edge_weights(G2)
    
    # Align the edge weights based on common edges
    g1_aligned, g2_aligned = align_edge_weights(g1_weights, g2_weights)
    
    # Calculate Pearson correlation
    pearson_corr, _ = pearsonr(g1_aligned, g2_aligned)
    
    # Calculate Spearman rank correlation
    spearman_corr, _ = spearmanr(g1_aligned, g2_aligned)
    
    return pearson_corr, spearman_corr

# Example usage
# Create two weighted graphs G1 and G2
# Create graphs using the edge lists
G1 = nx.Graph()
G1.add_weighted_edges_from(G1_edges)

G2 = nx.Graph()
G2.add_weighted_edges_from(G2_edges)

# Calculate correlations
pearson_corr, spearman_corr = calculate_edge_correlations(G1, G2)
print(f"Pearson Correlation: {pearson_corr}")
print(f"Spearman Rank Correlation: {spearman_corr}")


G1 edges: [(0, 1, {'weight': 78.0}), (0, 2, {'weight': 63.0}), (0, 3, {'weight': 93.0}), (0, 4, {'weight': 76.0}), (0, 5, {'weight': 92.0}), (0, 6, {'weight': 49.0}), (0, 7, {'weight': 48.0}), (1, 2, {'weight': 77.0}), (1, 3, {'weight': 60.0}), (1, 4, {'weight': 75.0}), (1, 5, {'weight': 80.0}), (1, 6, {'weight': 70.0}), (1, 7, {'weight': 59.0}), (2, 3, {'weight': 76.0}), (2, 4, {'weight': 54.0}), (2, 5, {'weight': 76.0}), (2, 6, {'weight': 68.0}), (2, 7, {'weight': 85.0}), (3, 4, {'weight': 84.0}), (3, 5, {'weight': 52.0}), (3, 6, {'weight': 52.0}), (3, 7, {'weight': 82.0}), (4, 5, {'weight': 48.0}), (4, 6, {'weight': 85.0}), (4, 7, {'weight': 77.0}), (5, 6, {'weight': 89.0}), (5, 7, {'weight': 62.0}), (6, 7, {'weight': 86.0})]
G2 edges: [(0, 1, {'weight': 0.00306659}), (0, 2, {'weight': 0.00345463}), (0, 3, {'weight': 0.00383706}), (0, 4, {'weight': 0.0040359}), (0, 5, {'weight': 0.00320574}), (0, 6, {'weight': 0.0033893}), (0, 7, {'weight': 0.00346077}), (1, 2, {'weight': 0.00212126

array([ 0., 81., 70., 70., 57., 86., 72., 63.])